# Generated by Django 4.1 on 2024-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectType', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'ProjectType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('project_des', models.TextField()),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projecttype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
    ]
