# Generated by Django 4.1 on 2024-03-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_des',
            new_name='project_description',
        ),
    ]
