# Generated by Django 4.1 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_model_remove_project_user_id_project_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('IM', 'Internal Medicine'), ('SU', 'Surgery'), ('PE', 'Pediatrics')], default='IM', max_length=2),
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
