# Generated by Django 4.1 on 2024-03-12 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_project_type_delete_projecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_name', models.CharField(max_length=128)),
                ('data_path', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='train_data/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'db_table': 'TrainData',
            },
        ),
    ]
